services:
  front:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: qna-next:1.0
    volumes:
      - ./app:/app/app/
      - /app/node_modules
    env_file:
      - .env.dev
    ports:
      - "3000:3000"